### ISSUE TITLE
No implementation found for method getCookies on channel webview_cookie_manager

### ISSUE THREAD

**Issue by lsdlh** [fryette/webview_cookie_manager#59]
webview_flutter: 3.0.0
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (2 weeks ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

E/flutter (10616): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCookies on channel webview_cookie_manager)
E/flutter (10616): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (10616): <asynchronous suspension>
E/flutter (10616): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
E/flutter (10616): <asynchronous suspension>
E/flutter (10616): #2      JdcookiePage.build.<anonymous closure> (package:jd_cookie/pages/jdcookie/view.dart:61:42)
E/flutter (10616): <asynchronous suspension>

**Comment by lsdlh** [comment]
Problems with hot refresh and hot start
